In [1]:
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np
from typing import Callable

In [3]:
def dense(x, W, b, activation):
    return activation(tf.matmul(x, W) + b)

In [15]:
x = np.random.randn(1,10)
W = tf.Variable(np.random.randn(10, 10))
b = tf.Variable(np.random.randn(1,10))

In [16]:
x @ W + b

<tf.Tensor: id=67, shape=(1, 10), dtype=float64, numpy=
array([[ 1.05096749, -1.26601666, -1.45583392,  1.5720686 , -0.4322612 ,
         1.69938904, -3.08727146,  6.28210875,  1.4634053 , -2.7596931 ]])>

In [17]:
print(dense(x, W, b, tf.sigmoid))

tf.Tensor(
[[0.74096064 0.2199399  0.18910534 0.8280783  0.39358651 0.84545492
  0.04363536 0.99813403 0.81205295 0.05954155]], shape=(1, 10), dtype=float64)


In [18]:
with tf.GradientTape() as tape:
    z = dense(x, W, b, tf.sigmoid)

In [19]:
y = np.random.randint(0,2,10)
y

array([1, 0, 1, 1, 1, 1, 0, 1, 1, 1])

In [20]:
loss =tf.keras.losses.categorical_crossentropy(y, z)
loss

<tf.Tensor: id=95, shape=(1,), dtype=float64, numpy=array([19.36698815])>

In [21]:
gradients=tape.gradient(loss, [W,b])
gradients

[None, None]

In [28]:
x

array([[-0.31337168, -0.92800188,  0.50350802,  0.05250709,  0.8143183 ,
        -0.60639133,  0.27085931, -1.10737336, -0.67667743, -0.38956157]])

In [29]:
W

<tf.Variable 'Variable:0' shape=(10, 10) dtype=float64, numpy=
array([[ 0.07297268,  1.32454277, -0.59718079,  0.73752961, -1.85201272,
        -1.02996744,  0.66441819, -0.86441012,  0.54089656, -1.84891749],
       [ 0.35938787,  1.76376287,  0.82953067,  0.15358846, -0.04617509,
        -0.12401388,  0.1691342 ,  0.27392022, -0.27571712,  0.42912261],
       [ 0.71799428, -0.68504716,  1.28526938,  0.07396679, -0.90576275,
         0.90426652, -0.72060686,  1.43219806,  0.83284663,  0.85528052],
       [ 1.52846801, -0.33621203,  0.76207095, -1.25047993, -0.34127098,
        -0.78360946,  0.52926572, -0.74823179,  1.11390304, -0.45908404],
       [-0.02658148, -0.28433961, -1.85304261, -0.7277642 ,  0.37197661,
         2.07023627, -0.09069212,  1.92813063, -0.71731545, -1.62619064],
       [ 0.04138043, -0.53199902,  0.34716552, -0.43904428, -0.68272191,
         0.07996541,  0.71802963,  1.10521645, -1.36352888,  1.3247759 ],
       [-0.56739034,  0.8953969 , -0.46824664,  0.05251